package th.co.ktb.dsl.model.common;

public enum RequestDocumentType {
	DSL202_POSTPONE_REQUEST_FORM,
	DSL203_CERTIFICATE_DEBT,
	RELATIONSHIP_EVIDENCE,
	ELDER_CARD,
	CERTIFIER_CARD,
	SALARY_CERTIFICATE,
	ACCOUNT_STATEMENT,
	CITIZEN_CARD,
	SALARY_SLIP_BEFORE,
	SALARAY_SLIP_AFTER,
	SUSPEND_REQUEST_FORM,
	INCOMPETENCE_CERTIFICATE,
	DISABILITY_CERTIFICATE,
	MEDICAL_CERTIFICATE;
}
