package th.co.ktb.dsl.model.postpone;

public enum PostponeDocumentType {
	DSL202_POSTPONE_REQUEST_FORM,
	DSL203_CERTIFICATE_DEBT,
	RELATIONSHIP_EVIDENCE,
	ELDER_CARD,
	CERTIFIER_CARD,
	SALARY_CERTIFICATE,
	ACCOUNT_STATEMENT,
	CITIZEN_CARD,
	SALARY_SLIP_BEFORE,
	SALARAY_SLIP_AFTER
}
